language: ruby
rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - 2.0.0
 - 2.1.5
 - 2.2.0
 - ruby-head

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq -y mplayer ffmpeg

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  except:
    - gh-pages

notifications:
  irc: "chat.freenode.net#lolcommits"

deploy:
  provider: rubygems
  api_key:
    secure: Y7FFOMDahITtHYRV3UQAw+BA2JbqoArN/Ii9PUTU6RaLmTIvpZBzqtvR3r8ah3SdXNh0Cx10gVf0pRc6HXKTNQdwMWCkOQwukAb+9kLDKFxl3x+w4X2u6yWmtsyNMTWK1gF4hEF1IHnsdg2dYEoFfE2M5bHex85ND/Q6820sPa8=
  gem: lolcommits
  on:
    tags: true
    all_branches: true
    repo: mroth/lolcommits
