version: "{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "187"
    - ruby_version: "192"
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "215"
    - ruby_version: "221"

clone_folder: c:\projects\lolcommits
clone_depth: 10
skip_tags: true

branches:
  except:
    - gh-pages

init:
  # stub mplayer/ffmpeg so it looks like they are installed
  - mkdir c:\bin
  - fsutil file createnew c:\bin\mplayer 1
  - fsutil file createnew c:\bin\ffmpeg 1
  - setx path "%path%;c:\bin"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - choco install imagemagick

before_build:
  #- icacls "%APPVEYOR_BUILD_FOLDER%\vendor\ext\CommandCam\CommandCam.exe" /grant:r "Administrators":RX
  #- icacls "%APPVEYOR_BUILD_FOLDER%\vendor\ext\imagesnap\imagesnap" /grant:r "Administrators":RX
  #- icacls "%APPVEYOR_BUILD_FOLDER%\vendor\ext\videosnap\videosnap" /grant:r "Administrators":RX
build_script:
  - bundle install

test_script:
  - bundle exec rake
